config/routes.rb
Rails.application.routes.draw do
  resources :bodydata
  root :to => 'bodydata#index'

end

app/models/bodydatum.rb
class Bodydatum < ActiveRecord::Base
#\.が小数点位置で\dが桁数
#  validates_format_of :weight, :with=>/\A\d+(\.\d)?\z/
#  validates_format_of :height, :with=>/\A\d+(\.\d)?\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bodydata_controller.rb
class BodydataController < ApplicationController
  before_action :set_bodydatum, only: [:show, :edit, :update, :destroy]

  # GET /bodydata
  # GET /bodydata.json
  def index
    @bodydata = Bodydatum.all
  end

  # GET /bodydata/1
  # GET /bodydata/1.json
  def show
  end

  # GET /bodydata/new
  def new
    @bodydatum = Bodydatum.new
  end

  # GET /bodydata/1/edit
  def edit
  end

  # POST /bodydata
  # POST /bodydata.json
  def create
    @bodydatum = Bodydatum.new(bodydatum_params)
    @bodydatum.height = @bodydatum.height.round(2)
    @bodydatum.weight = @bodydatum.weight.round(1)
    respond_to do |format|
      if @bodydatum.save
        format.html { redirect_to @bodydatum, notice: 'Bodydatum was successfully created.' }
        format.json { render action: 'show', status: :created, location: @bodydatum }
      else
        format.html { render action: 'new' }
        format.json { render json: @bodydatum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bodydata/1
  # PATCH/PUT /bodydata/1.json
  def update
    @bodydatum.height = @bodydatum.height.round(2)
    @bodydatum.weight = @bodydatum.weight.round(1)
    respond_to do |format|
      if @bodydatum.update(bodydatum_params)
        format.html { redirect_to @bodydatum, notice: 'Bodydatum was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @bodydatum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bodydata/1
  # DELETE /bodydata/1.json
  def destroy
    @bodydatum.destroy
    respond_to do |format|
      format.html { redirect_to bodydata_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bodydatum
      @bodydatum = Bodydatum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bodydatum_params
      params.require(:bodydatum).permit(:name, :weight, :height)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bodydata_helper.rb
module BodydataHelper
end

app/views/bodydata/_form.html.erb
<%= form_for(@bodydatum) do |f| %>
  <% if @bodydatum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bodydatum.errors.count, "error") %> prohibited this bodydatum from being saved:</h2>

      <ul>
      <% @bodydatum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :"名前" %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :"身長（小数点2桁まで）" %><br>
    <%= f.text_field :height %>
  </div>

  <div class="field">
    <%= f.label :"体重（小数点1桁まで）" %><br>
    <%= f.text_field :weight %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bodydata/edit.html.erb
<h1>Editing bodydatum</h1>

<%= render 'form' %>

<%= link_to 'Show', @bodydatum %> |
<%= link_to 'Back', bodydata_path %>

app/views/bodydata/index.html.erb
<h1>Listing bodydata</h1>

<table>
  <thead>
    <tr>
      <th>名前</th>
      <th>身長</th>
      <th>体重</th>
    </tr>
  </thead>

  <tbody>
    <% @bodydata.each do |bodydatum| %>
      <tr>
        <td><abbr title = "身長:<%= number_with_precision(bodydatum.height, precision: 2) %>&#13;&#10;体重:<%= number_with_precision(bodydatum.weight, precision: 1) %>"><%= bodydatum.name %></abbr></td>
        <td><%= number_with_precision(bodydatum.height, precision: 2) %></td>
        <td><%= number_with_precision(bodydatum.weight, precision: 1) %></td>
        <td><%= link_to '詳細', bodydatum, :title => "サンプル" %></td>
        <td><%= link_to '変更', edit_bodydatum_path(bodydatum) %></td>
        <td><%= link_to '削除', bodydatum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '新規登録', new_bodydatum_path %>

app/views/bodydata/new.html.erb
<h1>New bodydatum</h1>

<%= render 'form' %>

<%= link_to 'Back', bodydata_path %>

app/views/bodydata/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>名前:</strong>
  <%= @bodydatum.name %>
</p>

<p>
  <strong>身長:</strong>
  <%= number_with_precision(@bodydatum.height, precision: 2) %>
</p>

<p>
  <strong>体重:</strong>
  <%= number_with_precision(@bodydatum.weight, precision: 1) %>
</p>

<%= link_to 'Edit', edit_bodydatum_path(@bodydatum) %> |
<%= link_to 'Back', bodydata_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bodydata</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>